---

- name: remove containers on ECS nodes
  hosts: all
  gather_facts: no
  user: "{{ ECS.ssh_user }}"
  become: true
  become_user: root

    - name: remove filebeat container
      command: docker rm -f "{{ filebeat.container_name }}"
      ignore_errors: yes
      tags: filebeat

    - name: remove filebeat image
      command: docker rmi -f "{{ images.filebeat.image }}"
      ignore_errors: yes
      tags: filebeat

    - name: remove filebeat file
      file: dest="{{ destdir }}/{{ filebeat.config_dir }}" state=absent
      tags: filebeat
