---
- name: download beats docker images
  hosts: localhost
  connection: local
  tasks:
    - name: pull filebeat image
      command: docker pull "{{ images.filebeat.image }}"
      tags: filebeat

    - name: check for file
      stat: path="{{ tmpdir }}/{{ images.filebeat.filename }}"
      register: file_exists
      tags: filebeat

    - name: save filebeat image to local disk
      command: docker save -o "{{ tmpdir }}/{{ images.filebeat.filename }}" "{{ images.filebeat.image }}"
      #when: file_exists.stat.exists == False
      tags: filebeat
      
- name: copy filebeat image to remote nodes
  hosts: "{{ hosts | default('filebeat') }}"
  user: "{{ ECS.ssh_user }}"
  become: true
  become_method: sudo

  tasks:
    - name: Transfer filebeat image to remote nodes
      copy:  src="{{ tmpdir }}/{{ images.filebeat.filename }}" dest="{{ destdir }}/{{ filebeat.config_dir }}/"
      tags: filebeat

    - name: load filebeat image to docker
      command: docker load -i "{{ destdir }}/{{ filebeat.config_dir }}/{{ images.filebeat.filename }}"
      tags: filebeat
